---
- name: TLS | Ensure directories
  become: yes
  become_user: root
  file:
    path: "{{ tls.target_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755