---
- name: TLS | Local | Check that vars are filled properly
  fail:
    msg: "You have to fill tls.local_src_key and tls.local_src_cert vars"
  when: not tls.local_src_key or not tls.local_src_cert


- name: TLS | Local | Ensure certificate on target host
  become: yes
  copy:
    dest: "{{ tls.target_dir }}/{{ tls.target_cert_name }}"
    content: "{{ tls.local_src_cert }}"
    mode: 0644
    owner: root
    group: root

- name: TLS | Local | Ensure private key on target host
  become: yes
  copy:
    dest: "{{ tls.target_dir }}/{{ tls.target_key_name }}"
    content: "{{ tls.local_src_key }}"
    mode: 0600
    owner: root
    group: root
